/**
 * Synthetic ARES scenario primitives. These fixtures intentionally contain no
 * customer data and make no network calls.
 */

export const BASE_EVIDENCE = [
  {
    id: "E-001",
    type: "browser-telemetry",
    source: "Synthetic Microsoft Edge for Business navigation audit",
    summary: "Browser event BRW-20260718-084200-7F3A shows mira.patel@northstar.example completing an OAuth consent redirect from docs-review.example to Microsoft login on device FIN-LT-2047.",
    observedAt: "2026-07-18T08:42:00.000Z",
    collectedAt: "2026-07-18T08:47:00.000Z",
    freshnessMinutes: 5,
    reliability: 0.93,
    status: "observed",
    details: {
      eventId: "BRW-20260718-084200-7F3A",
      userPrincipalName: "mira.patel@northstar.example",
      sourceIp: "203.0.113.84",
      requestHost: "docs-review.example",
      redirectUri: "https://login.microsoftonline.com/common/oauth2/nativeclient",
      userAgent: "Edge 126 · Windows 11",
    },
    synthetic: true,
  },
  {
    id: "E-002",
    type: "identity-audit",
    source: "Synthetic Microsoft Entra ID audit log",
    summary: "Audit event 6c4f3d1e recorded user consent for DocuSync Pro (client suffix …D2D4), granting Mail.ReadWrite, Files.Read.All, and offline_access delegated permissions.",
    observedAt: "2026-07-18T08:43:00.000Z",
    collectedAt: "2026-07-18T08:47:00.000Z",
    freshnessMinutes: 4,
    reliability: 0.99,
    status: "observed",
    details: {
      activityDisplayName: "Consent to application",
      correlationId: "2b42e45c-62ad-4f90-a93b-fb51ce778d91",
      applicationId: "6cf6f8a2-b3f1-4f31-a1b7-9ab87e61d2d4",
      applicationName: "DocuSync Pro",
      consentType: "Principal",
      delegatedPermissions: ["Mail.ReadWrite", "Files.Read.All", "offline_access"],
    },
    synthetic: true,
  },
  {
    id: "E-003",
    type: "identity-session",
    source: "Synthetic Microsoft Entra ID sign-in log",
    summary: "Sign-in c55da0f1 accepted the DocuSync refresh token from 203.0.113.84 (fictional hosting ASN 64518, Bucharest) six minutes after consent; the session remains active.",
    observedAt: "2026-07-18T08:44:00.000Z",
    collectedAt: "2026-07-18T08:47:00.000Z",
    freshnessMinutes: 3,
    reliability: 0.98,
    status: "observed",
    details: {
      signInId: "c55da0f1-8807-42be-bd3c-5b1edbd73786",
      userPrincipalName: "mira.patel@northstar.example",
      resourceDisplayName: "Microsoft Graph",
      sourceIp: "203.0.113.84",
      location: "Bucharest, RO",
      authenticationRequirement: "Previously satisfied",
    },
    synthetic: true,
  },
  {
    id: "E-004",
    type: "mail-audit",
    source: "Synthetic Microsoft Purview Exchange audit",
    summary: "Operation New-InboxRule created rule 'Invoice archive' to forward messages matching invoice, payment, or beneficiary to ap-invoices@external-review.example and mark them read.",
    observedAt: "2026-07-18T08:45:00.000Z",
    collectedAt: "2026-07-18T08:48:00.000Z",
    freshnessMinutes: 3,
    reliability: 0.98,
    status: "observed",
    details: {
      operation: "New-InboxRule",
      mailbox: "mira.patel@northstar.example",
      ruleName: "Invoice archive",
      forwardTo: "ap-invoices@external-review.example",
      subjectContains: ["invoice", "payment", "beneficiary"],
      clientIp: "203.0.113.84",
    },
    synthetic: true,
  },
  {
    id: "E-005",
    type: "cloud-data-audit",
    source: "Synthetic Microsoft Purview SharePoint audit",
    summary: "Audit correlation sp-44219 links the session to 17 FileAccessed events in /sites/Finance/Payments, including Payment_Reconciliation_2026-07-18.xlsx.",
    observedAt: "2026-07-18T08:46:00.000Z",
    collectedAt: "2026-07-18T08:48:00.000Z",
    freshnessMinutes: 2,
    reliability: 0.97,
    status: "observed",
    details: {
      operation: "FileAccessed",
      workload: "SharePoint",
      siteUrl: "https://northstar.sharepoint.com/sites/Finance",
      objectId: "Shared Documents/Payments/Payment_Reconciliation_2026-07-18.xlsx",
      userId: "mira.patel@northstar.example",
      clientIp: "203.0.113.84",
    },
    synthetic: true,
  },
  {
    id: "E-006",
    type: "endpoint-detection",
    source: "Synthetic Microsoft Defender for Endpoint advanced-hunting snapshot",
    summary: "Device FIN-LT-2047 reported healthy sensor telemetry through 08:46 UTC with no matching process, browser-extension, persistence, or credential-theft detection; this bounded negative result is not proof the host is clean.",
    observedAt: "2026-07-18T08:46:00.000Z",
    collectedAt: "2026-07-18T08:49:00.000Z",
    freshnessMinutes: 3,
    reliability: 0.96,
    status: "negative",
    details: {
      deviceName: "FIN-LT-2047",
      deviceId: "a9f6d14e-7627-48d5-aee4-6ce9306ebf47",
      sensorHealth: "Active",
      alertCount: 0,
      lookbackWindow: "24 hours",
      lastSeen: "2026-07-18T08:46:12Z",
    },
    synthetic: true,
  },
  {
    id: "E-007",
    type: "identity-directory",
    source: "Synthetic Microsoft Entra ID directory snapshot",
    summary: "mira.patel@northstar.example is assigned Finance Operations access with no Entra, Azure subscription, Exchange, or SharePoint administrator role.",
    observedAt: "2026-07-18T08:40:00.000Z",
    collectedAt: "2026-07-18T08:49:00.000Z",
    freshnessMinutes: 9,
    reliability: 0.99,
    status: "observed",
    details: {
      userPrincipalName: "mira.patel@northstar.example",
      objectId: "d12049bb-3a33-4b0f-bac6-e258bb7f3233",
      department: "Finance Operations",
      directoryRoles: ["None"],
      privilegedGroups: ["None"],
      accountEnabled: true,
    },
    synthetic: true,
  },
  {
    id: "E-008",
    type: "business-service-map",
    source: "Synthetic ServiceNow business-service and ownership register",
    summary: "FIN-LT-2047 and its user support the 14:00 UTC same-day payroll approval window, payment reconciliation, and the controlled vendor-master review process.",
    observedAt: "2026-07-18T08:30:00.000Z",
    collectedAt: "2026-07-18T08:49:00.000Z",
    freshnessMinutes: 19,
    reliability: 0.94,
    status: "observed",
    details: {
      serviceId: "BIZ-PAY-007",
      serviceName: "Same-day payroll approval",
      businessOwner: "Finance Operations",
      settlementCutoff: "14:00 UTC",
      recoveryTimeObjective: "60 minutes",
      criticalityTier: "Tier 1",
    },
    synthetic: true,
  },
];

export const MALWARE_EVIDENCE = [
  {
    id: "E-101",
    type: "endpoint-detection",
    source: "Synthetic Microsoft Defender for Endpoint alert",
    summary: "Defender alert MDE-ALRT-784219 observed UpdateReview.exe executing from Mira Patel's browser cache on FIN-LT-2047 and classified the behavior as credential theft.",
    observedAt: "2026-07-18T08:46:30.000Z",
    collectedAt: "2026-07-18T08:49:00.000Z",
    freshnessMinutes: 2.5,
    reliability: 0.99,
    status: "observed",
    details: {
      alertId: "MDE-ALRT-784219",
      deviceName: "FIN-LT-2047",
      accountName: "NORTHSTAR\\mira.patel",
      processName: "UpdateReview.exe",
      processPath: "C:\\Users\\mira.patel\\AppData\\Local\\Temp\\EdgeCache\\UpdateReview.exe",
      severity: "High",
    },
    synthetic: true,
  },
  {
    id: "E-102",
    type: "browser-forensics",
    source: "Synthetic Microsoft Defender for Endpoint browser-forensics capture",
    summary: "DeviceFileEvents correlation DFE-559031 recorded UpdateReview.exe opening the Edge Network/Cookies database used by Mira Patel's active Microsoft 365 profile; no cookie values are retained in the fixture.",
    observedAt: "2026-07-18T08:46:45.000Z",
    collectedAt: "2026-07-18T08:49:00.000Z",
    freshnessMinutes: 2.25,
    reliability: 0.98,
    status: "observed",
    details: {
      correlationId: "DFE-559031",
      deviceName: "FIN-LT-2047",
      initiatingProcess: "UpdateReview.exe",
      targetFile: "Users/mira.patel/AppData/Local/Microsoft/Edge/User Data/Default/Network/Cookies",
      accessOperation: "FileOpened",
      retainedSecretMaterial: "None",
    },
    synthetic: true,
  },
  {
    id: "E-103",
    type: "endpoint-forensics",
    source: "Synthetic Microsoft Defender for Endpoint process tree",
    summary: "Process tree MDE-TREE-118402 links UpdateReview.exe to a user-level Edge extension loader registered under extension ID kpfdbfnhcpmjodlcnaddkacagmejigdp, with persistence scoped to Mira Patel's profile.",
    observedAt: "2026-07-18T08:47:00.000Z",
    collectedAt: "2026-07-18T08:49:00.000Z",
    freshnessMinutes: 2,
    reliability: 0.97,
    status: "observed",
    details: {
      processTreeId: "MDE-TREE-118402",
      parentProcess: "msedge.exe",
      childProcess: "UpdateReview.exe",
      extensionId: "kpfdbfnhcpmjodlcnaddkacagmejigdp",
      persistenceScope: "Current user",
      signerStatus: "Unsigned",
    },
    synthetic: true,
  },
  {
    id: "E-104",
    type: "network-telemetry",
    source: "Synthetic Netskope secure web gateway event",
    summary: "Gateway event NSWG-20260718-449103 allowed FIN-LT-2047 to establish TLS to cdn-session-check.example at reserved IP 192.0.2.146; the request began 31 seconds after UpdateReview.exe launched.",
    observedAt: "2026-07-18T08:47:15.000Z",
    collectedAt: "2026-07-18T08:49:00.000Z",
    freshnessMinutes: 1.75,
    reliability: 0.96,
    status: "observed",
    details: {
      eventId: "NSWG-20260718-449103",
      deviceName: "FIN-LT-2047",
      destinationHost: "cdn-session-check.example",
      destinationIp: "192.0.2.146",
      destinationPort: 443,
      policyAction: "Allowed and logged",
    },
    synthetic: true,
  },
];

export const BASE_NODES = [
  { id: "N-THREAT", type: "ThreatActor", label: "External attacker", role: "source", evidenceIds: ["E-001"] },
  { id: "N-PHISH", type: "AttackTechnique", label: "OAuth consent phishing", role: "transit", evidenceIds: ["E-001", "E-002"] },
  { id: "N-GRANT", type: "CloudGrant", label: "Malicious delegated OAuth grant", role: "control-plane", evidenceIds: ["E-002"] },
  { id: "N-SESSION", type: "CloudSession", label: "Active Microsoft 365 session", role: "transit", evidenceIds: ["E-003"] },
  { id: "N-MAILBOX", type: "SaaSAsset", label: "Finance mailbox", role: "transit", evidenceIds: ["E-004"] },
  { id: "N-FRAUD", type: "BusinessImpact", label: "Payment instruction manipulation", role: "target", evidenceIds: ["E-004", "E-008"] },
  { id: "N-SHAREPOINT", type: "DataAsset", label: "Finance/Payments library", role: "target", evidenceIds: ["E-005"] },
  { id: "N-PAYROLL", type: "BusinessProcess", label: "Same-day payroll approval", role: "target", evidenceIds: ["E-008"] },
  { id: "N-USER", type: "Identity", label: "Finance employee", role: "context", evidenceIds: ["E-007", "E-008"] },
  { id: "N-ENDPOINT", type: "Endpoint", label: "Finance workstation", role: "context", evidenceIds: ["E-006"] },
];

export const BASE_EDGES = [
  { id: "G-001", from: "N-THREAT", to: "N-PHISH", type: "initiates", claimClass: "observed", evidenceIds: ["E-001"] },
  { id: "G-002", from: "N-PHISH", to: "N-GRANT", type: "creates", claimClass: "observed", evidenceIds: ["E-001", "E-002"] },
  { id: "G-003", from: "N-GRANT", to: "N-SESSION", type: "authorizes", claimClass: "observed", evidenceIds: ["E-002", "E-003"] },
  { id: "G-004", from: "N-SESSION", to: "N-MAILBOX", type: "accesses", claimClass: "observed", evidenceIds: ["E-003", "E-004"] },
  { id: "G-005", from: "N-MAILBOX", to: "N-FRAUD", type: "enables", claimClass: "hypothesis", evidenceIds: ["E-004", "E-008"] },
  { id: "G-006", from: "N-SESSION", to: "N-SHAREPOINT", type: "accesses", claimClass: "observed", evidenceIds: ["E-003", "E-005"] },
  { id: "G-007", from: "N-SESSION", to: "N-PAYROLL", type: "could-disrupt", claimClass: "hypothesis", evidenceIds: ["E-003", "E-008"] },
];

export const MALWARE_NODES = [
  { id: "N-MALWARE", type: "Malware", label: "Credential stealer", role: "transit", evidenceIds: ["E-101", "E-103"] },
  { id: "N-BROWSER-TOKEN", type: "CredentialArtifact", label: "Browser session cookie", role: "transit", evidenceIds: ["E-102"] },
];

export const MALWARE_EDGES = [
  { id: "G-101", from: "N-THREAT", to: "N-MALWARE", type: "operates", claimClass: "derived", evidenceIds: ["E-101", "E-104"] },
  { id: "G-102", from: "N-MALWARE", to: "N-ENDPOINT", type: "executes-on", claimClass: "observed", evidenceIds: ["E-101", "E-103"] },
  { id: "G-103", from: "N-ENDPOINT", to: "N-BROWSER-TOKEN", type: "exposes", claimClass: "observed", evidenceIds: ["E-101", "E-102"] },
  { id: "G-104", from: "N-BROWSER-TOKEN", to: "N-SESSION", type: "replays", claimClass: "derived", evidenceIds: ["E-102", "E-003"] },
  { id: "G-105", from: "N-ENDPOINT", to: "N-PAYROLL", type: "could-disrupt", claimClass: "hypothesis", evidenceIds: ["E-101", "E-008"] },
];

export const ACTIONS = [
  {
    id: "A-IDENTITY-CONTAIN",
    title: "Revoke OAuth sessions and malicious grant",
    description: "Revoke active sessions, remove the delegated grant, and delete the external inbox rule.",
    category: "identity-containment",
    mitigatesNodeIds: ["N-GRANT"],
    evidenceIds: ["E-002", "E-003", "E-004", "E-005"],
    disruption: 0.08,
    urgency: 0.95,
    reversibility: 0.95,
    requiresApproval: true,
    approvalRole: "incident-commander",
    tradeoffs: ["Forces the user to reauthenticate", "May interrupt active Microsoft 365 work"],
    simulation: {
      summary: "Identity access is revoked in simulation; no production control is changed.",
      expectedSignals: ["Active session count reaches zero", "DocuSync Pro grant is absent", "External inbox rule is absent"],
    },
  },
  {
    id: "A-ENDPOINT-ISOLATE",
    title: "Isolate the finance workstation",
    description: "Simulate network isolation of the endpoint while preserving EDR management traffic.",
    category: "endpoint-containment",
    mitigatesNodeIds: ["N-ENDPOINT"],
    evidenceIds: ["E-006"],
    malwareEvidenceIds: ["E-101", "E-102", "E-103", "E-104"],
    disruption: 0.42,
    urgency: 0.55,
    malwareUrgency: 0.98,
    reversibility: 0.8,
    requiresApproval: true,
    approvalRole: "incident-commander",
    tradeoffs: ["Interrupts payroll work on this device", "Requires an alternate workstation"],
    simulation: {
      summary: "Endpoint network isolation is simulated; no production endpoint is changed.",
      expectedSignals: ["Business network connections are blocked", "EDR control channel remains available"],
    },
  },
  {
    id: "A-COMBINED-CONTAIN",
    title: "Isolate endpoint and revoke cloud access",
    description: "Coordinate endpoint isolation with session, OAuth grant, and inbox-rule revocation.",
    category: "combined-containment",
    mitigatesNodeIds: ["N-GRANT", "N-ENDPOINT"],
    evidenceIds: ["E-002", "E-003", "E-004", "E-005", "E-006"],
    malwareEvidenceIds: ["E-002", "E-003", "E-004", "E-005", "E-101", "E-102", "E-103", "E-104"],
    disruption: 0.58,
    urgency: 0.92,
    malwareUrgency: 0.98,
    reversibility: 0.7,
    requiresApproval: true,
    approvalRole: "ciso-delegate",
    tradeoffs: ["Highest immediate disruption", "Needs coordinated identity and endpoint owners"],
    simulation: {
      summary: "Combined cloud and endpoint containment is simulated; no production control is changed.",
      expectedSignals: ["All enumerated paths are interrupted", "Cloud sessions are revoked", "Endpoint is isolated"],
    },
  },
  {
    id: "A-MONITOR",
    title: "Continue enhanced monitoring",
    description: "Preserve access and increase identity, mail, cloud-data, and endpoint monitoring.",
    category: "observe",
    mitigatesNodeIds: [],
    evidenceIds: ["E-001", "E-002", "E-003", "E-004", "E-005", "E-006"],
    disruption: 0.02,
    urgency: 0.4,
    reversibility: 1,
    requiresApproval: false,
    approvalRole: "soc-lead",
    tradeoffs: ["Does not interrupt an active attack path", "Extends attacker dwell time if compromise persists"],
    simulation: {
      summary: "Enhanced monitoring is simulated; access remains unchanged.",
      expectedSignals: ["Telemetry collection continues", "No containment control is applied"],
    },
  },
];
